site_name: Kind k8s local
nav:
  - Home: 'index.md'
  - Cluster: 'cluster.md'
  - Metrics-Server: 'metrics-server.md'
  - MetalLB: 'metal-lb.md'
theme:
  name: material
  schema: slate
  palette: 
    - scheme: default
      accent: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy