site_name: Kind k8s local
nav:
  - Home: 'index.md'
  - Cluster: 'cluster.md'
theme:
  name: material
  schema: slate
  palette: 
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.code.copy