apiVersion: v1
kind: Service
metadata:
  name: flutter-test-svc
  labels:
    app.kubernetes.io/name: flutter-test
    app.kubernetes.io/instance: flutter-test
    app.kubernetes.io/environment: flutter
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: flutter-test
    app.kubernetes.io/instance: flutter-test
    app.kubernetes.io/environment: flutter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-test
  labels:
    app.kubernetes.io/name: flutter-test
    app.kubernetes.io/instance: flutter-test
    app.kubernetes.io/environment: flutter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flutter-test
      app.kubernetes.io/instance: flutter-test
      app.kubernetes.io/environment: flutter
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app.kubernetes.io/name: flutter-test
        app.kubernetes.io/instance: flutter-test
        app.kubernetes.io/environment: flutter
    spec:
      containers:
        - name: flutter-test
          image: "dotnetnat/project-mnt:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 300m
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 30
            tcpSocket:
              port: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flutter-web-vs
spec:
  hosts:
    - "flutter.kind.local"
  gateways:
    - "istio-system/local-gateway"
  http:
    - match:
        - uri:
            prefix: /
      rewrite:
        uri: /
      route:
        - destination:
            host: flutter-test-svc
            port:
              number: 8080
